name: pending md file

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can change this to another supported environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run Script
      run: |
        cd pending
        ./pending_md_linux.sh

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Apply changes from GitHub Action"
        git push
